### PR TITLE
Update normalization option and shape variations storing

### PR DESCRIPTION
**Pull request by davidwalter2**
- fixed a bug where the variations were normalized incorrectly
- subtract 1 ndf in case distribution was normalized
- Save all systematic variations with prefit and postfit shapes

### CODE REVIEW

**Comment by bendavid** [comment]
Can you edit the PR description to reflect the last fix? (ie logkhalfdiff is no longer set to 0)

**Comment by davidwalter2** [comment]
It's the first bullet point, the halfdiff was only set to 0 in the PR before fixing the bug

**Comment by bendavid** [comment]
Yes but the PR description still says "set logkhalfdiff to 0 after normalizing" which is no longer the case right?

**Comment by davidwalter2** [comment]
> Yes but the PR description still says "set logkhalfdiff to 0 after normalizing" which is no longer the case right?

OK corrected

**Pull request merged**
